### ISSUE TITLE
Could not find browser revision 818858 (Laravel Homestead)

### ISSUE THREAD

**Issue by danielcharrua** [rialto-php/puphpeteer#126]
**Describe the bug**
Cant launch puphpeteer on a Laravel Homestead box.
Just installed the Homestead box and a fresh Laravel 8 app with puphpeteer as shown on the docs.
```
Nesk\Rialto\Exceptions\Node\FatalException
Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
```

**Reproducible example**
Just using the default example on the puphpeteer homepage.
```
$puppeteer = new Puppeteer();
$browser = $puppeteer->launch();

$page = $browser->newPage();
$page->goto('https://google.com');

$browser->close();
```

**Expected behavior**
Get puphpeteer running on the Homestead Box.

**Generated logs**
No logs, I can't finish the execution, an exception is thrown when running `$browser = $puppeteer->launch();`

**Environment:**
 - OS: Ubuntu 18.04
 - Node version: 12.20.0
 - PHP version: 8.0.0

**My Node package manager is:**
NPM 7.0.8

**Comment by grenadecx** [comment]
I hade the same problem. After som digging it appears that puppeter doesn't run it's browser installation script. I solved it by manually running:

node node_modules/puppeteer/install.js (for default chromium installation)

Remember you also need dependencies for the browser. I found that the following dependencies was required in Ubuntu 18.04:

sudo apt-get install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

You can always add it as a script to the package.json file in laravel.

With this said, I don't think this is an issue with this package. The problem appears to be with puppeteer node module.

**Comment by nesk** [comment]
Since this doesn't seem related to this project I'm closing the issue. If you ever find something new, tell me and we will see if we reopen it.

**Comment by Astriel** [comment]
I'm having the same problem on a production server too :-)

**Comment by nesk** [comment]
Did you try to see if @grenadecx answer's could solve your problem?

Still, I don't think it's related to this project. Try to see if [Puppeteer's troubleshooting guide](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) can help you.

**Comment by danielcharrua** [comment]
@nesk @grenadecx I will try your solution in a few moments and let you know how it comes, in the mean time, if this is an issue with puppeteer node module, how can we solve it? maybe creating an issue?

I have installed puppeteer directly using node in another project without any issues and it seems to run the browser installation script. So why when installing the puphpeteer package, puppeteer is not installing browser scripts? Any ideas?

**Comment by danielcharrua** [comment]
I'm using Mac so it seems that puppeteer installed the `mac-818858` browser and not the `linux-818858` used in Homestead (Ubuntu 18.04).

As @grenadecx said, you need to install the browser on the Homestead VM under the Laravel project running:

`node node_modules/puppeteer/install.js`

In my case before installing the browser dependencies I need to run `sudo apt-get update` and then:

`sudo apt-get install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils`

After running these scripts I was able to run puppeteer from PHP 🚀

Thank you @nesk @grenadecx
