### ISSUE TITLE
some body help me please

### ISSUE THREAD

**Issue by meladkadies** [rialto-php/puphpeteer#131]
Symfony\Component\Process\Exception\ProcessFailedException
The command "node "C:\xampp\htdocs\cario24\vendor\nesk\rialto\src/node-process/serve.js" C:\xampp\htdocs\cario24\vendor\nesk\puphpeteer\src\PuppeteerConnectionDelegate.js "{""idle_timeout"":60,""log_node_console"":false,""log_browser_console"":false}"" failed. Exit Code: 1(General error) Working directory: C:\xampp\htdocs\cario24\public Output: ================ Error Output: ================ 'node' is not recognized as an internal or external command, operable program or batch file.

**Comment by nesk** [comment]
[The `executable_path` option](https://github.com/rialto-php/rialto/blob/dev/docs/api.md#options) can be used to provide a custom path to Node if you need.
