### ISSUE TITLE
Could not find browser revision 818858

### ISSUE THREAD

**Issue by egyleader** [rialto-php/puphpeteer#159]
**Describe the bug**
when running the scrapper for the first time it gives this error :
`Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.`

where can I configure the browser type and executable path ??
and how can I run this `PUPPETEER_PRODUCT=firefox npm install" ` command ?

**Comment by rickgoemans** [comment]
I had the same problem using a docker environment.

I did the `npm install @nesk/puphpeteer` command on my Macbook and therefore it ran `node node_modules/puppeteer/install.js` which results in downloading the mac os binary image.

The solution is either one of these options:

- Running the `npm install @nesk/pupheteer` from inside the execution (in my case docker) environment
- Manually running the install script from inside the execution (in my case docker) environment by running `node node_modules/puppeteer/install.js`.

**Comment by egyleader** [comment]
thanks that solves it
