### ISSUE TITLE
Cannot be required on Laravel 9 due dependency problems with symfony/process

### ISSUE THREAD

**Issue by DerFichtl** [rialto-php/puphpeteer#171]
**Describe the bug**

> sail composer require nesk/puphpeteer

    - nesk/rialto[1.2.0, ..., 1.3.0] require symfony/process ^3.3|^4.0 -> found symfony/process[v3.3.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev] but the package is fixed to v6.0.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - nesk/rialto 1.4.0 requires symfony/process ^3.3|^4.0|^5.0 -> found symfony/process[v3.3.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - nesk/puphpeteer 2.0.0 requires nesk/rialto ^1.2.0 -> satisfiable by nesk/rialto[1.2.0, 1.2.1, 1.3.0, 1.4.0].
    - Root composer.json requires nesk/puphpeteer ^2.0 -> satisfiable by nesk/puphpeteer[2.0.0].

**Expected behavior**
Composer should not fail on that.

**Environment (please complete the following information):**
 - OS: macOS
 - PHP version: 8.1
 - Laravel: 9

**Comment by eusonlito** [comment]
Duplicated https://github.com/rialto-php/puphpeteer/issues/170
