### ISSUE TITLE
Call to a member function getProperty() on null

### ISSUE THREAD

**Issue by kennethtomagan** [rialto-php/puphpeteer#66]
When trying to get the `innerText` or `innerHTML` of table data that have a null value, 
```
$report->latitude = $row->querySelector('td[name="cell__formLatitude"]')->getProperty('innerHTML');
```

return an error. 
```
Call to a member function getProperty() on null
```
Does anyone encounter this issue? How to solve this?

**Comment by nesk** [comment]
Please provide a reproducible example.
